import type { Config } from "tailwindcss";

export default {
  content: ["src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        bg: "var(--bg)",
        "bg-elevated": "var(--bg-elevated)",
        surface: "var(--surface)",
        "surface-hover": "var(--surface-hover)",
        "surface-active": "var(--surface-active)",
        primary: "var(--primary)",
        "primary-hover": "var(--primary-hover)",
        "primary-active": "var(--primary-active)",
        "primary-subtle": "var(--primary-subtle)",
        text: "var(--text)",
        "text-secondary": "var(--text-secondary)",
        "text-tertiary": "var(--text-tertiary)",
        "text-brand": "var(--text-brand)",
        "text-brand-hover": "var(--text-brand-hover)",
        "text-on-brand": "var(--text-on-brand)",
        border: "var(--border)",
        "border-strong": "var(--border-strong)",
        divider: "var(--divider)",
        ring: "var(--ring)",
        success: "var(--success)",
        "success-subtle": "var(--success-subtle)",
        warning: "var(--warning)",
        "warning-subtle": "var(--warning-subtle)",
        error: "var(--error)",
        "error-subtle": "var(--error-subtle)",
        info: "var(--info)",
        "accent-signal": "var(--accent-signal)",
        "accent-signal-subtle": "var(--accent-signal-subtle)",
      },
      spacing: {
        "space-0": "var(--space-0)",
        "space-1": "var(--space-1)",
        "space-2": "var(--space-2)",
        "space-3": "var(--space-3)",
        "space-4": "var(--space-4)",
        "space-5": "var(--space-5)",
        "space-6": "var(--space-6)",
        "space-8": "var(--space-8)",
        "space-10": "var(--space-10)",
        "space-12": "var(--space-12)",
        "space-16": "var(--space-16)",
        "space-20": "var(--space-20)",
        "space-24": "var(--space-24)",
      },
      borderRadius: {
        sm: "4px",
        DEFAULT: "8px",
        md: "8px",
        lg: "12px",
        xl: "16px",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
      },
      fontSize: {
        "2xs": ["11px", { lineHeight: "1.4" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
